services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: spu0987
      POSTGRES_DB: skywingsdb
    ports:
      - "3030:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
      image: adminer
      container_name: adminer
      environment:
        ADMINER_DEFAULT_SERVER: db
      ports:
        - "8080:8080"

volumes:
  postgres_data: