services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: spu0987
      POSTGRES_DB: skywingsdb
    ports:
      - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: